name: Build python-webscraper Docker Image CI

# on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

on:
  push:
    tags: 
      - '**'
  release:
    types: [published,released]  # Trigger only on release published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Docker image tag based on the current timestamp
      - name: Set up IMAGE_TAG
        id: tag
        run: echo "IMAGE_TAG=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image from the moneycontrol_data_get directory
      - name: Build the Docker image
        run: |
          docker build ./moneycontrol_data_get \
            --file ./moneycontrol_data_get/Dockerfile \
            --tag ${{ secrets.DOCKER_USERNAME }}/python-webscraper:${{ env.IMAGE_TAG }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/python-webscraper:latest

      # Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-webscraper:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/python-webscraper:latest
