name: Run python-webscraper Docker Container

on:
  # push:
    # branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_run:
    workflows: ["Build python-webscraper Docker Image CI"]
    types:
      - completed

jobs: 
  run-container:
    runs-on: ubuntu-latest

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull the latest Docker image from Docker Hub
      - name: Pull the Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/python-webscraper:latest

      # Run the Docker container
      - name: Run the Docker container
        run: |
          docker run --name python-webscraper-container \
            ${{ secrets.DOCKER_USERNAME }}/python-webscraper:latest
